name: Test Only please remove me

on:
  pull_request:
    branches: '*'
  workflow_dispatch:
    inputs:
      git-ref:
        description: Git Ref (Optional)
        required: false
#  push:
#    tags:
#    - 'v*'

permissions:
  contents: write

jobs:
  create-release-test:
    runs-on: ubuntu-latest
    steps:
      - name: Create Release Test
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          omitBody: true
          prerelease: true
          draft: true
          token: ${{ secrets.GITHUB_TOKEN }}

  build-native:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/romange/ubuntu-dev:20
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: Configure & Build
      run: |
          apt update && apt install -y debhelper
    - name: Build artifacts
      run: |
          # Work around https://github.com/actions/checkout/issues/766
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          git describe --always --tags ${{ github.sha }}
          ./tools/release.sh
    - name: Generate packages
      run: |
          # once the build is over, we want to generate a Debian package
          ./tools/packaging/generate_debian_package.sh build-opt/dragonfly-x86_64
    - name: Save artifacts
      run: |
          # place all artifacts at the same location
          mkdir -p results-artifacts
          mv build-opt/dragonfly-*tar.gz results-artifacts
          mv dragonfly_*.deb results-artifacts
          ls -lha results-artifacts/*
